package com.example.hotspotscheck.models

import androidx.compose.runtime.Composable

data class City(val id: String, val name: String, val img: String, val hotspots: List<Hotspot>)

data class Hotspot(val id: String, val name: String, val img: List<String>, val text: String, var visitdate: String?)




fun getCities(): List<City> {
    return listOf(
        City(
            id = "1",
            name = "New York",
            img = "https://www.godominicanrepublic.com/wp-content/uploads/2018/03/newyork-64819822_xxl.jpg",
            hotspots = listOf(
            Hotspot(id = "1", name = "Empire State Building", img = listOf("https://marvel-b1-cdn.bc0a.com/f00000000179470/www.esbnyc.com/sites/default/files/styles/small_feature/public/2019-10/home_banner-min.jpg?itok=uZt-03Vw", "https://thebettervacation.com/wp-content/uploads/2021/06/Inside-Empire-State-Building-1024x576.jpg", "https://untappedcities.com/wp-content/uploads/2019/11/Empire-State-Building-80th-Floor-Redesigned-Observatory-NYC-012.jpg", "https://galeriemagazine.com/wp-content/uploads/2019/07/190727_c2019_EvanJoseph_EmpireStateBuildingObservatory-4.jpg"), text = "Empire State Building, steel-framed skyscraper rising 102 stories that was completed in New York City in 1931 and was the tallest building in the world until 1971. The Empire State Building is located in Midtown Manhattan, on Fifth Avenue at 34th Street. It remains one of the most distinctive and famous buildings in the United States and is one of the best examples of Modernist Art Deco design.", visitdate = "Zeljko"),
            Hotspot(id = "2", name = "Top of the Rock", img = listOf("https://media02.stockfood.com/largepreviews/MjE4MTA5NDM3Mw==/70357883-Tourists-Admiring-the-Panoramic-View-Over-Manhattan-From-the-Top-of-the-Rock-Observation-Deck-in-the-Ge.jpg", "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/64/68/68/new-york-traumblick-auf.jpg?w=1200&h=-1&s=1", "https://thebettervacation.com/wp-content/uploads/2021/05/Top-of-the-Rock-New-York.jpg", "https://mediaim.expedia.com/localexpert/184267/7e7c4dd0-4556-4c82-94f9-f69938ab9255.jpg?impolicy=resizecrop&rw=1005&rh=565"), text = "The views of NYC from Top of the Rock are not to be missed. Sharing the warm air and sweeping views of Central Park and Manhattan's Midtown and downtown skyscrapers with family and friends is an experience that is truly unforgettable.", visitdate = null),
            Hotspot(id = "3", name = "Circle Line Cruise", img = listOf("https://cdn.getyourguide.com/img/tour/0dfe187f32955809.jpeg/146.jpg", "https://mediaim.expedia.com/localexpert/586683/6c7e0845-a4fb-4da9-b695-ec031ce54e21.jpg?impolicy=resizecrop&rw=1005&rh=565", "https://upload.wikimedia.org/wikipedia/commons/e/ef/Circle_Line_X.jpg"), text = "Circle Line Sightseeing Cruises is a boat-based sightseeing and entertainment company in Manhattan, New York. Its principal business is operating guided tours of New York City from its base at Pier 83 in the Hell's Kitchen neighborhood.", visitdate = null),
            Hotspot(id = "4", name = "Edge", img = listOf("https://cdn.prod.www.spiegel.de/images/48f82c15-838c-4855-819a-ae641d8ca17b_w1200_r1.33_fpx72.57_fpy50.jpg", "https://cdn.prod.www.spiegel.de/images/bfc61afe-e5eb-4d53-ac9c-dd9679a987ea_w1600_r1.4991462720546387_fpx30.01_fpy55.jpg", "https://cdn.prod.www.spiegel.de/images/582adfc3-3d5d-478b-a1df-0e2c39bb99cb_w1600_r1.5_fpx51.33_fpy55.01.jpg", "https://image.stern.de/9175210/t/3o/v2/w1440/r1.7778/-/the-edge-new-york-aussichtsplattform.jpg"), text = "Edge is the highest sky deck in the Western Hemisphere located at 30 Hudson Yards, with a one-of-a-kind design, it’s suspended in mid-air, giving you the feeling of floating in the sky with 360-degree views you can’t get anywhere else.", visitdate = null),
            Hotspot(id = "5", name = "Central Park Zoo", img = listOf("https://blog.playandtour.com/wp-content/uploads/2017/03/nueva-york-central-park-zoo-delacorte-reloj.jpg", "https://media.holidaycheck.com/data/urlaubsbilder/images/193/1156170347.jpg", "https://image.newyorkcity.de/wp-content/uploads/2017/05/Central-Park-Zoo-Tickets.jpg", "https://img3.oastatic.com/img2/17092954/600x300r/central-park-zoo.jpg"), text = "You will find over 130 species at the Central Park Zoo - from giant Grizzly Bears to tiny Leaf Cutter Ants.", visitdate = null),
            Hotspot(id = "6", name = "NY Aquarium", img = listOf("https://afar-production.imgix.net/uploads/images/post_images/images/yLyRK7tDDk/original_9678f51ddef311fd9936ceea4ba264c0.jpg?1549376797?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=entropy&fit=crop&h=719&q=80&w=954", "https://eventective-media.azureedge.net/2402339_lg.jpg", "https://www.nymetroparents.com/columnpic2/aquariums-in-the-new-york-area.jpg", "https://cdn0.weddingwire.com/vendor/733210/3_2/960/jpg/1536938883-1d81d7c42f4d6f0f-1536938881-a65454444d238d37-1536938876444-3-IMG_1980.jpeg"), text = "The New York Aquarium is the oldest continually operating aquarium in the United States, located on the Riegelmann Boardwalk in Coney Island, Brooklyn, New York City. As of 2018, the New York Aquarium consists of five exhibits: Aquatheater; Conservation Hall; Sea Cliffs; Spineless; and Ocean Wonders: Sharks.", visitdate = null),
            )
        ),
        City(
            id = "2",
            name = "London",
            img = "https://germanbackpacker.com/wp-content/uploads/2018/10/London-Eye-Preise-Erfahrungen-2-e1539963321177.jpg",
            hotspots = listOf(
                Hotspot(id = "1", name = "Trafalgar Square", img = listOf("https://bitmap.ticketlens.com/poi/265308607/1200x1200", "https://cdn.londonandpartners.com/asset/trafalgar-square-2c4ac9626a4fcce79cc7cbd8c4c30642.jpg", "https://www.ebooking.com/de/nachrichten/wp-content/uploads/2013/01/Trafalgar-Square.jpg", "https://thumbs.dreamstime.com/b/trafalgar-square-und-national-gallery-london-uk-august-die-architektur-kunst-attraktion-blau-br%C3%BCchig-britisch-geb%C3%A4ude-157533899.jpg"), text = "The Trafalgar Square is one of London's most vibrant spaces in the middle of the city. Find out about the history of this heritage site, its statues and its fountains. Trafalgar Square is surrounded by museums, galleries, cultural spaces and historic buildings.", visitdate = null),
                Hotspot(id = "2", name = "Buckingham Palace", img = listOf("https://images-ext-1.discordapp.net/external/CpH1ll737YOXvEMIHLr5KGbEFxdGIdxG2MsjaSgElhQ/https/upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Natural_History_Museum_London_Jan_2006.jpg/800px-Natural_History_Museum_London_Jan_2006.jpg", "https://upload.wikimedia.org/wikipedia/commons/b/b4/Buckingham_Palace%2C_London_-_April_2009.jpg", "https://www.london-kurztrip.de/images/slider/lonbuc/slider2.jpg", "https://media0.faz.net/ppmedia/aktuell/2058682496/1.6316002/default-retina/wie-ein-geist-steht-das-kleid.jpg"), text = "Buckingham Palace is recognised around the world as the home of The Queen, the focus of national and royal celebrations such as the Platinum Jubilee, as well as the backdrop to the regular Changing the Guard ceremony.", visitdate = null),
                Hotspot(id = "3", name = "History Museum", img= listOf("https://www.p.city-walks.info/London/Buckingham-Palace.jpg", "https://www.travelling-britain.com/images/1612260-_x500-nocrop.jpg", "https://www.imago-images.de/bild/st/0085392863/w.jpg", "https://media.cool-cities.com/natural_history_museum_lon_001pecl_x_mob.jpg?h=730"), text = "Discover ancient civilisations, learn from the incredible achievements and challenges of people and societies past and present, and immerse yourself in the culture, languages, environments, people and debates of our ever-changing world. ", visitdate = null),
                Hotspot(id = "4", name = "Tower Bridge", img= listOf("https://res.cloudinary.com/rebelwalls/image/upload/b_black,c_fill,f_auto,fl_progressive,h_533,q_auto,w_800/v1428566434/article/R11641_image1", "https://london.sehenswuerdigkeiten-online.de/sehenswuerdigkeiten/img/tobr1l.jpg", "https://image.stern.de/7357276/t/pE/v4/w1440/r1.7778/-/china-fake-tower-bridge.jpg", "https://images.adsttc.com/media/images/58b8/0b79/e58e/cecc/aa00/0309/large_jpg/17022118_10155149285429759_504899691150313683_n.jpg?1488456564"), text = "Tower Bridge crosses the Thames from the Tower of London in the north to Shad Thames on the South Bank. You can walk or drive across it, but for the best views, visit the exhibition to access the high level walkways. It’s also worth being on the riverbank when the bridge opens to allow tall-masted ships to pass through.", visitdate = null),
                Hotspot(id = "5", name= "Big Ben", img= listOf("https://imgsrv2.voi.id/AqJDpiqhkIXkbcmeg2mDmEscRW2zCvy25JcGA0BO7A0/auto/1280/853/sm/1/bG9jYWw6Ly8vcHVibGlzaGVycy82NTk1LzIwMjAwNTMxMTUzNC1tYWluLmNyb3BwZWRfMTU5MDkxNDA5NC5qcGVn.jpg", "https://www1.wdr.de/radio/wdr4/wort/zur-sache/brexit-220~_v-fullhd.jpg", "https://newsmobile.in/wp-content/uploads/2017/08/Big-Ben.jpg", "https://cdn.getyourguide.com/img/tour/5cf63524dcb7a.jpeg/99.jpg"), text= "The Houses of Parliament and Elizabeth Tower, commonly called Big Ben, are among London's most iconic landmarks and must-see London attractions. Technically, Big Ben is the name given to the massive bell inside the clock tower, which weighs more than 13 tons.  The clock tower looks spectacular at night when the four clock faces are illuminated.", visitdate = null),
                Hotspot(id = "6", name= "Hyde Park", img= listOf("https://images-ext-2.discordapp.net/external/Eftr5986QhMF5EURR_Rl3vhpzX72pCBT7k5bqW1EoOM/https/mywowo.net/media/images/cache/londra_hyde_park_03_kensington_gardens_jpg_1200_630_cover_85.jpg?width=1166&height=612", "https://cdn.getyourguide.com/img/location/54d387b957abb.jpeg/99.jpg", "https://d1e00ek4ebabms.cloudfront.net/production/7787c61a-0de8-4295-b9bc-b1e308bf05b1.jpg", "https://www.hydeparkint.co.uk/blog/wp-content/uploads/2016/06/shutterstock_428001.jpg"), text= "Hyde Park covers 142 hectares (350 acres), making it the largest park in central London. It is the city’s most important green lung and where many tourists and residents come to relax and enjoy a bit of fresh air.", visitdate = null),

                )
        ),
        City(
            id = "3",
            name = "Tokyo",
            img = "https://www.falstaff.at/fileadmin/_processed_/7/1/csm_1-tokio-c-GettyImages-2640_22025df6c6.jpg",
            hotspots = listOf(
                Hotspot(id = "1", name = "Meguro River", img = listOf("https://upload.wikimedia.org/wikipedia/commons/8/85/Meguro_River_Spring_2014%282%29.jpg", "https://static.gltjp.com/glt/prd/data/directory/12000/11030/20200605_141755_ff99ef4c_w1920.jpg", "https://i.ytimg.com/vi/RAVmCUmCuR8/maxresdefault.jpg", "https://i.ytimg.com/vi/DsAwEbPpB5Y/maxresdefault.jpg"), text = "The Meguro River is a river which flows through Tokyo, Japan. Its tributaries include the Kitazawa River and the Karasuyama River. The river flows into Tokyo Bay near the Tennōzu Isle Station.", visitdate = null),
                Hotspot(id = "2", name = "Yoyogi Park", img = listOf("https://upload.wikimedia.org/wikipedia/commons/f/f3/Fountain_Yoyogipark.JPG", "https://gaijinpot.scdn3.secure.raxcdn.com/app/uploads/sites/6/2016/09/Yoyogi-park-lead.jpg", "https://img5.goodfon.com/wallpaper/nbig/9/bc/iaponiia-tokio-yoyogi-park-park-prud-fontan-derevia-tsveteni.jpg", "https://www.worldatlas.com/r/w768/upload/22/72/67/shutterstock-1063931900.jpg"), text = "Yoyogi Park is a park in Yoyogikamizonocho, Shibuya, Tokyo, Japan, located adjacent to Harajuku Station and Meiji Shrine. The park is a popular Tokyo destination. On Sundays, it is especially busy when it is used as a gathering place for Japanese rock music fans, jugglers, comedians, martial arts clubs, cosplayers and other subculture and hobby groups.", visitdate = null),
                Hotspot(id = "3", name = "Chidorigafuchi", img = listOf("https://oddviser.com/photo/place/1600/393.jpg", "https://jw-webmagazine.com/wp-content/uploads/2019/07/jw-5d1b4a389efe24.29566576.jpeg", "https://media.timeout.com/images/105726649/image.jpg", "https://i0.wp.com/www.tokyostreetview.com/wp-content/uploads/2018/04/TokyoMoat.jpg?fit=1280%2C720&ssl=1"), text = "The Chidorigafuchi Trench is one of the best places in Tokyo to see the cherry blossoms in spring, from late March to early April. This 700-meter walk next to the Imperial Palace moat offers beautiful scenery and great opportunities for discovery.", visitdate = null),
                Hotspot(id = "4", name = "Shinjuku Central Park", img= listOf("https://i.pinimg.com/originals/24/28/e5/2428e5946542ba757c864117a3a2b298.jpg", "https://media.timeout.com/images/103944932/750/422/image.jpg", "https://m.justgola.com/media/a/00/07/30715_og_1.jpeg", "https://ak-d.tripcdn.com/images/100w190000016cx80EE8A.jpg?proc=source%2Ftrip"), text = "Shinjuku Central Park, Tokyo, Japan, covers an area of more than 80,000 square meters. The green area in Shinjuku is second only to Shijuku Gyoen National Garden, Meiji Jingu Gaien, and Toyama Park. It is also the park with the largest green area in Shinjuku District.", visitdate = null),
                Hotspot(id = "5", name = "Shinjuku", img = listOf("https://www.gotokyo.org/de/story/guide/shinjuku-shop/images/shopping_guide.jpg", "https://www.thewholeworldisaplayground.com/wp-content/uploads/2018/04/Japan-Things-to-do-in-Shinjuku-Tokyo.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Colorful_neon_street_signs_in_Kabukich%C5%8D%2C_Shinjuku%2C_Tokyo.jpg/1024px-Colorful_neon_street_signs_in_Kabukich%C5%8D%2C_Shinjuku%2C_Tokyo.jpg", "https://gaijinpot.scdn3.secure.raxcdn.com/app/uploads/sites/4/2017/03/Shinjuku-City-512910636.jpg"), text = "Shinjuku is one of the 23 city wards of Tokyo, but the name commonly refers to just the large entertainment, business and shopping area around Shinjuku Station. Shinjuku Station is the world's busiest railway station, handling more than two million passengers every day.", visitdate = null),
                Hotspot(id = "6", name = "Sensō-ji Temple", img = listOf("https://img.fotocommunity.com/sensoji-tempel-tokyo-a5dfad3c-6ffe-4ef3-ac70-2089acf5c6ce.jpg?height=1080", "https://mywowo.net/media/images/cache/tokyo_03_tempio_buddista_senso_ji_jpg_1200_630_cover_85.jpg", "https://www.westend61.de/images/0001242451pw/sensoji-temple-in-cherry-blossom-season-tokyo-japan-asia-RHPLF06215.jpg", "https://www.japan-guide.com/g18/3001_01.jpg"), text = "Sensoji is a Buddhist temple located in Asakusa. It is one of Tokyo's most colorful and popular temples. The temple was completed in 645, making it Tokyo's oldest temple.", visitdate = null)

       )
   )





     /*   City(
            id = "1",
            name = "New York",
            img = "https://www.godominicanrepublic.com/wp-content/uploads/2018/03/newyork-64819822_xxl.jpg",
            hotspots = listOf(
            Hotspot(id = "1", name = "Empire State Building", img = "https://marvel-b1-cdn.bc0a.com/f00000000179470/www.esbnyc.com/sites/default/files/styles/small_feature/public/2019-10/home_banner-min.jpg?itok=uZt-03Vw", text = "Empire State Building, steel-framed skyscraper rising 102 stories that was completed in New York City in 1931 and was the tallest building in the world until 1971. The Empire State Building is located in Midtown Manhattan, on Fifth Avenue at 34th Street. It remains one of the most distinctive and famous buildings in the United States and is one of the best examples of Modernist Art Deco design."),
            Hotspot(id = "2", name = "Top of the Rock", img = "https://media02.stockfood.com/largepreviews/MjE4MTA5NDM3Mw==/70357883-Tourists-Admiring-the-Panoramic-View-Over-Manhattan-From-the-Top-of-the-Rock-Observation-Deck-in-the-Ge.jpg", text = "The views of NYC from Top of the Rock are not to be missed. Sharing the warm air and sweeping views of Central Park and Manhattan's Midtown and downtown skyscrapers with family and friends is an experience that is truly unforgettable."),
            Hotspot(id = "3", name = "Circle Line Cruise", img = "https://cdn.getyourguide.com/img/tour/0dfe187f32955809.jpeg/146.jpg", text = "Circle Line Sightseeing Cruises is a boat-based sightseeing and entertainment company in Manhattan, New York. Its principal business is operating guided tours of New York City from its base at Pier 83 in the Hell's Kitchen neighborhood."),
            Hotspot(id = "4", name = "Edge", img = "https://cdn.prod.www.spiegel.de/images/48f82c15-838c-4855-819a-ae641d8ca17b_w1200_r1.33_fpx72.57_fpy50.jpg", text = "Edge is the highest sky deck in the Western Hemisphere located at 30 Hudson Yards, with a one-of-a-kind design, it’s suspended in mid-air, giving you the feeling of floating in the sky with 360-degree views you can’t get anywhere else."),
            Hotspot(id = "5", name = "Central Park Zoo", img = "https://blog.playandtour.com/wp-content/uploads/2017/03/nueva-york-central-park-zoo-delacorte-reloj.jpg", text = "You will find over 130 species at the Central Park Zoo - from giant Grizzly Bears to tiny Leaf Cutter Ants."),
            Hotspot(id = "6", name = "NY Aquarium", img = "https://afar-production.imgix.net/uploads/images/post_images/images/yLyRK7tDDk/original_9678f51ddef311fd9936ceea4ba264c0.jpg?1549376797?ixlib=rails-0.3.0&auto=format%2Ccompress&crop=entropy&fit=crop&h=719&q=80&w=954", text = "The New York Aquarium is the oldest continually operating aquarium in the United States, located on the Riegelmann Boardwalk in Coney Island, Brooklyn, New York City. As of 2018, the New York Aquarium consists of five exhibits: Aquatheater; Conservation Hall; Sea Cliffs; Spineless; and Ocean Wonders: Sharks."),
            )
        ),
        City(
            id = "2",
            name = "London",
            img = "https://germanbackpacker.com/wp-content/uploads/2018/10/London-Eye-Preise-Erfahrungen-2-e1539963321177.jpg",
            hotspots = listOf(
                Hotspot(id = "7", name = "Trafalgar Square", img ="https://bitmap.ticketlens.com/poi/265308607/1200x1200", text = "The Trafalgar Square is one of London's most vibrant spaces in the middle of the city. Find out about the history of this heritage site, its statues and its fountains. Trafalgar Square is surrounded by museums, galleries, cultural spaces and historic buildings."),
                Hotspot(id = "8", name = "Buckingham Palace", img ="https://images-ext-1.discordapp.net/external/CpH1ll737YOXvEMIHLr5KGbEFxdGIdxG2MsjaSgElhQ/https/upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Natural_History_Museum_London_Jan_2006.jpg/800px-Natural_History_Museum_London_Jan_2006.jpg", text = "Buckingham Palace is recognised around the world as the home of The Queen, the focus of national and royal celebrations such as the Platinum Jubilee, as well as the backdrop to the regular Changing the Guard ceremony."),
                Hotspot(id = "9", name = "History Museum", img="https://www.p.city-walks.info/London/Buckingham-Palace.jpg", text = "Discover ancient civilisations, learn from the incredible achievements and challenges of people and societies past and present, and immerse yourself in the culture, languages, environments, people and debates of our ever-changing world. "),
                Hotspot(id = "10", name = "Tower Bridge", img="https://res.cloudinary.com/rebelwalls/image/upload/b_black,c_fill,f_auto,fl_progressive,h_533,q_auto,w_800/v1428566434/article/R11641_image1", text = "Tower Bridge crosses the Thames from the Tower of London in the north to Shad Thames on the South Bank. You can walk or drive across it, but for the best views, visit the exhibition to access the high level walkways. It’s also worth being on the riverbank when the bridge opens to allow tall-masted ships to pass through."),
                Hotspot(id = "11", name= "Big Ben", img="https://imgsrv2.voi.id/AqJDpiqhkIXkbcmeg2mDmEscRW2zCvy25JcGA0BO7A0/auto/1280/853/sm/1/bG9jYWw6Ly8vcHVibGlzaGVycy82NTk1LzIwMjAwNTMxMTUzNC1tYWluLmNyb3BwZWRfMTU5MDkxNDA5NC5qcGVn.jpg", text= "The Houses of Parliament and Elizabeth Tower, commonly called Big Ben, are among London's most iconic landmarks and must-see London attractions. Technically, Big Ben is the name given to the massive bell inside the clock tower, which weighs more than 13 tons.  The clock tower looks spectacular at night when the four clock faces are illuminated."),
                Hotspot(id = "12", name= "Hyde Park", img="https://images-ext-2.discordapp.net/external/Eftr5986QhMF5EURR_Rl3vhpzX72pCBT7k5bqW1EoOM/https/mywowo.net/media/images/cache/londra_hyde_park_03_kensington_gardens_jpg_1200_630_cover_85.jpg?width=1166&height=612", text= "Hyde Park covers 142 hectares (350 acres), making it the largest park in central London. It is the city’s most important green lung and where many tourists and residents come to relax and enjoy a bit of fresh air."),

                )
        ),
        City(
            id = "3",
            name = "Tokyo",
            img = "https://www.falstaff.at/fileadmin/_processed_/7/1/csm_1-tokio-c-GettyImages-2640_22025df6c6.jpg",
            hotspots = listOf(
                Hotspot(id = "13", name = "Meguro River", img = "https://upload.wikimedia.org/wikipedia/commons/8/85/Meguro_River_Spring_2014%282%29.jpg", text = "The Meguro River is a river which flows through Tokyo, Japan. Its tributaries include the Kitazawa River and the Karasuyama River. The river flows into Tokyo Bay near the Tennōzu Isle Station."),
                Hotspot(id = "14", name = "Yoyogi Park", img = "https://upload.wikimedia.org/wikipedia/commons/f/f3/Fountain_Yoyogipark.JPG", text = "Yoyogi Park is a park in Yoyogikamizonocho, Shibuya, Tokyo, Japan, located adjacent to Harajuku Station and Meiji Shrine. The park is a popular Tokyo destination. On Sundays, it is especially busy when it is used as a gathering place for Japanese rock music fans, jugglers, comedians, martial arts clubs, cosplayers and other subculture and hobby groups."),
                Hotspot(id = "15", name = "Chidorigafuchi", img = "https://oddviser.com/photo/place/1600/393.jpg", text = "The Chidorigafuchi Trench is one of the best places in Tokyo to see the cherry blossoms in spring, from late March to early April. This 700-meter walk next to the Imperial Palace moat offers beautiful scenery and great opportunities for discovery."),
                Hotspot(id = "16", name = "Shinjuku Central Park", img="https://i.pinimg.com/originals/24/28/e5/2428e5946542ba757c864117a3a2b298.jpg", text = "Shinjuku Central Park, Tokyo, Japan, covers an area of more than 80,000 square meters. The green area in Shinjuku is second only to Shijuku Gyoen National Garden, Meiji Jingu Gaien, and Toyama Park. It is also the park with the largest green area in Shinjuku District."),
                Hotspot(id = "17", name = "Shinjuku", img = "https://www.gotokyo.org/de/story/guide/shinjuku-shop/images/shopping_guide.jpg", text = "Shinjuku is one of the 23 city wards of Tokyo, but the name commonly refers to just the large entertainment, business and shopping area around Shinjuku Station. Shinjuku Station is the world's busiest railway station, handling more than two million passengers every day."),
                Hotspot(id = "18", name = "Sensō-ji Temple", img = "https://img.fotocommunity.com/sensoji-tempel-tokyo-a5dfad3c-6ffe-4ef3-ac70-2089acf5c6ce.jpg?height=1080", text = "Sensoji is a Buddhist temple located in Asakusa. It is one of Tokyo's most colorful and popular temples. The temple was completed in 645, making it Tokyo's oldest temple.")

            )
        )*/
    )
}